### ISSUE TITLE
Firmware built for jive doesn't have wifi support

### ISSUE THREAD

**Issue by kalon33** [ralph-irving/squeezeos#2]
When updating to latest firmware for jive, there seems to be no network support (no network icon, no possibility to connect to a wifi or list networks). Is that expected? Where could be the problem?

Best regards.

**Comment by ralph-irving** [comment]
This was fixed in https://github.com/ralph-irving/squeezeos/commit/d052fc59eee36a2593f178f365b8420fa37964e2.
We have to use the prebuilt binary modules as the source is not available for the wifi kernel modules of the controller and force the kernel git revision to match.
I don't own a controller so I had the enlist the help of mh.
Please note that the default branch is now public/8.0
